### ISSUE TITLE
Brand-Manufacturer not Being pulled properly after order confirmation

### ISSUE THREAD

**Issue by CNCJP** [webchills/zencart-ec-analytics#1]
First time signing up and using Github. I posted in zencart forum but think this is the place to put this based on Readme. Shown below is code from order confirmation page on a new installation of zencart 1.5.4 with only this module. You can see that Bug's Life shows a brand of Microsoft and should be Warner. Have proven this with some other products as well during tests.  

`        ga('ec:addProduct', {   'id': '8', 'name': 'A Bug\'s Life Linked', 'brand': 'Microsoft', 'category': 'Cartoons', 'variant': 'n/a', 'price':  '35.99', 'quantity': '1', 'coupon': 'n/a', 'position': '0' } );
        ga('ec:addProduct', {   'id': '105', 'name': 'A Maximum Sample of 1', 'brand': 'Matrox', 'category': 'Big Linked', 'variant': 'n/a', 'price':  '50.00', 'quantity': '1', 'coupon': 'n/a', 'position': '1' } );      
 `

Trying this module with my own cart I get all n/a for brands. Though everything shows properly on every product and checkout page. So thats how I came to trying this on a new installation. Not sure if related but seemed like a bug on a new installation. 

I am not a coder only a alter to change minor things. So I looked to try to figure this out and I have no clue. Any questions or would like me to test I would be happy too just let me know. 

PS If my current site has coding issues unrelated to this I would be more then willing to pay for someone to fix them and install this module as well to get brand to pass. 
Thanks
Jamey

**Comment by CNCJP** [comment]
I found the solution after trying again for a few hours. This will be my first commit. Please double check my work though. Not sure if I should try to submit to zencart or is this something you will take care of.  In any case will post in the forum where I posted the question initially for others.

Change line 217 Change "orders_products_id" to "products_id"

`   $varTxt = ($variant->fields['products_options_values'] != "") ? $variant->fields['products_options_values']:"n/a";
$brand = zen_get_products_manufacturers_name($items_in_cart->fields['orders_products_id']); 
                         $brandTxt = ($brand != "") ? $brand:"n/a";`

**Comment by CNCJP** [comment]
Change line 217 of file in classes/observers/class.ec_analytics.php

Change below code from "orders_products_id" to "products_id"

$brand = zen_get_products_manufacturers_name($items_in_cart->fields['orders_products_id']);

**Comment by webchills** [comment]
Thank for reporting this typo preventing the brand from beeing recorded!
Your fix is included in version 1.2.1
